<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-BN2B2LR" ignored="1" name="Test(failed)" tests="6" failures="1" timestamp="05 Mar 2019 05:51:59 GMT" time="0.005" errors="0">
  <testcase name="run" time="0.001" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.0" classname="testng1.RetryA">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng1.RetryA.run(RetryA.java:13)
at testng1.rerunner.runn(rerunner.java:17)
... Removed 51 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run2" time="0.0" classname="testng1.RetryA">
    <ignored/>
  </testcase> <!-- run2 -->
</testsuite> <!-- Test(failed) -->
