<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-BN2B2LR" ignored="0" name="Test" tests="7" failures="1" timestamp="05 Mar 2019 05:50:25 GMT" time="0.105" errors="0">
  <testcase name="run" time="0.013" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.003" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.011" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.004" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.005" classname="testng1.RetryA">
    <skipped/>
  </testcase> <!-- run -->
  <testcase name="run" time="0.003" classname="testng1.RetryA">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng1.RetryA.run(RetryA.java:13)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run2" time="0.004" classname="testng1.RetryA"/>
</testsuite> <!-- Test -->
